language: ruby
cache: bundle
rvm:
  - 2.6
  - 2.5
  - 2.4
  - jruby-9.2.7.0
  - jruby-head
  - truffleruby-head
before_install:
  - gem install bundler
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
env:
  global:
    - JRUBY_OPTS='-J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Djruby.compile.mode=OFF -J-Djruby.compile.invokedynamic=false'
gemfile:
  - gemfiles/Gemfile.actionpack5.2
  - gemfiles/Gemfile.actionpack5.1
  - gemfiles/Gemfile.actionpack5.0
  - gemfiles/Gemfile.actionpack4.0
  - Gemfile
