language: ruby
cache: bundle
sudo: false
rvm:
  - 1.9.3
  - 2.2.2
  - jruby
  - jruby-head
  - rbx-2
env:
  global:
    - JRUBY_OPTS='-J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Djruby.compile.mode=OFF -J-Djruby.compile.invokedynamic=false'
gemfile:
  - Gemfile
  - gemfiles/Gemfile.actionpack3.2
  - gemfiles/Gemfile.actionpack4.0
  - gemfiles/Gemfile.actionpack4.2
script: bundle exec rake
