language: ruby
cache: bundle
sudo: false
rvm:
  - 2.4.1
  - jruby-9.1.14.0
  - jruby-head
before_install:
  - gem install bundler
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
env:
  global:
    - JRUBY_OPTS='-J-XX:+TieredCompilation -J-XX:TieredStopAtLevel=1 -J-Djruby.compile.mode=OFF -J-Djruby.compile.invokedynamic=false'
gemfile:
  - gemfiles/Gemfile.actionpack5.0.0
  - gemfiles/Gemfile.actionpack4.0
  - Gemfile
