name: CI

on:
  push:
    branches: [master]

  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    continue-on-error: ${{ endsWith(matrix.ruby, 'head') || matrix.gemfile == 'gemfiles/rails_edge.gemfile' }}

    strategy:
      matrix:
        ruby:
          # MRI
          - head
          - "3.1.0"
          - "3.0"
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"

          # JRuby
          - jruby-9.3
          - jruby-9.4

          # TruffleRuby
          - truffleruby-23.0

        gemfile:
          - Gemfile
          - gemfiles/rails_edge.gemfile # 7.1.0.alpha
          - gemfiles/rails_6.1.gemfile
          - gemfiles/rails_6.0.gemfile
          - gemfiles/rails_5.2.gemfile

        # Include additional ruby/gemfile combinations:
        include:
          # NOTE(ivy): Rails 7 requires Ruby version >= 2.7
          - ruby: "2.6"
            gemfile: Gemfile
          - ruby: "2.6"
            gemfile: gemfiles/rails_6.0.gemfile
          - ruby: "2.6"
            gemfile: gemfiles/rails_5.2.gemfile
        exclude:
          # NOTE(ivy): Rails 7 requires Ruby version >= 2.7
          - ruby: jruby-9.3
            gemfile: gemfiles/rails_edge.gemfile
          - ruby: jruby-9.2
            gemfile: gemfiles/rails_edge.gemfile


    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}

    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake
      - run: bundle exec rubocop
